defaults: &defaults
  docker:
    - image: circleci/node:8.11.4


version: 2
jobs:
  lint:
    <<: *defaults
    steps:
    - checkout
    - run: npm run lint
  build:
    <<: *defaults
    steps:
    - checkout
    - run: npm run build


workflows:
  version: 2
  build_and_lint:
    jobs:
    - lint
    - build
